const express=require("express")
const router=express.Router()
const {allBanners,addBanners,editBanner,addBannersSettings,getOne,uploadPic,deleteBanner,getOneBanner,isActiveBanner,isActiveBanners,search}=require("../contollers/bannerController")
const {protect}=require("../contollers/loginController")
router.get("/",allBanners)
router.get("/getOne",getOne)
router.get("/getOneBanner",getOneBanner)
router.post("/addBanner",protect,addBanners)
router.post("/editBanner",protect,editBanner)
router.post("/uploadPic",protect,uploadPic)
router.get("/bannerSetting",addBannersSettings)
router.post("/isActiveBanner",protect,isActiveBanners)
// router.get("/searchAdmin",search)
router.delete("/",deleteBanner)
module.exports=router