const express=require("express")
const router=express.Router()
const {getMain, addCommerce,getAll,getOne,editCommmerce,deleteCommerce,deletePic,addCategory,getCategory,deleteCategory,getCategorySimple,addPic,search}=require("../contollers/commerceController")
const {protect}=require("../contollers/loginController")

router.get("/",getMain)
router.post("/",protect, addCommerce)
router.delete("/",protect, deleteCommerce)
router.get("/getAll", getAll)
router.get("/getOne",getOne)
router.post("/edit",protect, editCommmerce)
router.delete("/pic",protect, deletePic)
router.post("/addPic",protect, addPic)
router.post("/addCategory",protect, addCategory)
router.get("/getCategory",getCategory)
router.get("/getCategorySimple",getCategorySimple)
router.delete("/deleteCategory",protect, deleteCategory)
router.get("/searchAdmin",search)
module.exports=router
