const express=require("express")
const router=express.Router()
const {getMain,addEvent,deleteEvent,getOneEvent,editEvent,loadMore,getAll,getTags,addPicture,isActiveEvent,getOneEventFront,search}=require("../contollers/eventController")
const { protect } = require("../contollers/loginController")
router.get("/",getMain)
router.get("/getAll",getAll)
router.post("/addEvent",protect, addEvent)
router.post("/addPicture",protect,addPicture)
router.get("/getOne",getOneEvent)
router.get("/getOneFront",getOneEventFront)
router.post("/edit",protect, editEvent)
router.get("/loadMore",loadMore)
router.post("/isActiveEvents",protect, isActiveEvent)
router.delete("/",protect,deleteEvent)
router.get("/tag",getTags)
router.get("/searchAdmin",search)
module.exports=router