const express=require("express")
const router=express.Router()
const{addIndustry,addSubcategory,editSubcategory,getAll,getOneIndsutry,editIndustry, deleteIndustry, deleteSubcategory,getOneSubcategory,addPic, getAllFront}=require("../contollers/industryController")
const { protect } = require("../contollers/loginController")
router.get("/",getAll)
router.get("/front",getAllFront)
router.post("/",protect, addIndustry)
router.delete("/",protect,deleteIndustry)
router.get("/getOne",getOneIndsutry)
router.post("/edit",protect,editIndustry)
router.post("/addPic",protect,addPic)
router.get("/subcategory",protect,getOneSubcategory)
router.post("/subcategory",protect,addSubcategory)
router.post("/subcategory/edit",protect, editSubcategory)
router.delete("/subcategory",protect,deleteSubcategory)
module.exports=router