const express=require("express")
const { protect } = require("../contollers/loginController")
const router=express.Router()
const {mainMembers,addMember,getOne,editMember,deleteMember,allMembers,addPic,addFile,deleteFile,getBycategory,search,download}=require("../contollers/memberController")
router.get("/",allMembers)
router.get("/main",mainMembers)
router.get("/category",getBycategory)
router.post("/add",protect, addMember)
router.get("/getOne",getOne)
router.post("/addPic",protect,addPic)
router.post("/addFile",protect,addFile)
router.post("/edit",protect,editMember)
router.delete("/",protect,deleteMember)
router.delete("/deleteFile",protect,deleteFile)
router.get("/searchAdmin",protect,search)
router.get("/download",download)
module.exports=router
